name: Test ast-github-action 

on: push

jobs:
  unittesting:
    runs-on: ubuntu-latest

    name: Unit Testing
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      
      - name: Run with empty client and secret
        id: empty_client_secret
        uses: ./
        with:
          project_name: test project
          base_uri: https:// 
          cx_client_id: 
          cx_client_secret: 
          scan_types: sast
      - name: Check if failed authentication
        if: ${{contains( steps.empty_client_secret.outputs.cxcli, 'Failed to authenticate') == false}}
        run:  |
          echo "The authentication must fail if invalid client id or password is used"
          exit 1
      
      - name: Valid scenario 
        id: valid_scenario
        uses: ./
        with:
          project_name: Integration project
          base_uri: https://master.cxast.com
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          scan_types: sast
      - name: Check output contains
        if: ${{ contains( steps.valid_scenario.outputs.cxcli, 'Completed') == false}}
        run: |
          echo "The cli failed"