name: Update checkmarx ast cli
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-checkmarx-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Latest Checkmarx API version
        id: checkmarx-ast-cli
        run: |
          echo ::set-output name=release_tag::$(curl -sL https://api.github.com/repos/checkmarx/ast-cli/releases/latest | jq -r ".tag_name")
          echo ::set-output name=current_tag::$(<checkmarx-ast-cli.version)
      - name: Update Checkmarx cli version
        if: steps.checkmarx-ast-cli.outputs.current_tag != steps.checkmarx-ast-cli.outputs.release_tag
        run: |
          # Update current release
          echo ${{ steps.checkmarx-ast-cli.outputs.release_tag }} > checkmarx-ast-cli.version
          sed -i 's/${{ steps.checkmarx-ast-cli.outputs.current_tag }}/${{ steps.checkmarx-ast-cli.outputs.release_tag }}/g' Dockerfile

      - name: Create Pull Request
        if: steps.checkmarx-ast-cli.outputs.current_tag != steps.checkmarx-ast-cli.outputs.release_tag
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          commit-message: Update checkmarx-ast-cli to ${{ steps.checkmarx-ast-cli.outputs.release_tag }}
          title: Update checkmarx-ast-cli Docker image with ${{ steps.checkmarx-ast-cli.outputs.release_tag }}
          body: |
            Updates [checkmarx-ast-cli][1] to ${{ steps.checkmarx-ast-cli.outputs.release_tag }}

            Auto-generated by [create-pull-request][2]

            [1]: https://github.com/Checkmarx/ast-cli
          labels: dependencies, automated pr
          branch: feature/update_cli